- name: generate config
  copy:
    content: "{{ GOBGP_CONF | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
    dest: /etc/gobgpd/gobgpd.conf
    validate: "gobgpd -t yml -f %s -d"
  notify: reload gobgpd
