- name: Check if gobgpd is installed.
  command: gobgpd --version
  register: gobgpd_exits_result
  failed_when: GOBGP_VERSION not in  gobgpd_exits_result.stdout
  changed_when: false
  ignore_errors: true

- name: Check if gobgp is installed.
  command: gobgp --version
  register: gobgp_exits_result
  failed_when: GOBGP_VERSION not in  gobgpd_exits_result.stdout
  changed_when: false
  ignore_errors: true

- import_tasks: common.yml
  when: (gobgp_exits_result.failed) and (gobgpd_exits_result.failed)

- import_tasks: generate_config.yml